---
project_name: saddle_detection
output_dir: /scratch/tmp/n_herr03/leezencounter/runs/
model: ../test/model/backup.pt

# for a full list of training and augmentation arguments see:
# https://docs.ultralytics.com/modes/train/#train-settings
train_args:
  mode: train
  task: detect
  # yamllint disable-line rule:line-length
  data: ../test/dataset/YOLO/combined_preprocessed_yolo_dataset.yaml
  epochs: 200
  save: true
  val: true
  plots: true
  rect: true
  pretrained: true
  cache: true
  verbose: true
  device: mps
  batch: 0.7
  nbs: 32
  multi_scale: true
  workers: 7
  amp: true
  dropout: 0.1
  # Augmentation Parameters
  hsv_s: 0.7    # hue
  hsv_h: 0.015  # saturation
  hsv_v: 0.5    # brightness
  degrees: 180
  flipud: 0.1
  fliplr: 0.5
  mosaic: 1.0
